### ISSUE TITLE
Layer Performance Tracking Issue

### ISSUE THREAD

**Issue by jzulauf-lunarg** [KhronosGroup/Vulkan-ValidationLayers#1001]
All Validation Layer Performance information is now tracked via the Validation Layer Performance project [page](https://github.com/KhronosGroup/Vulkan-ValidationLayers/projects/6). Please feel free to add cards to that project, or to create new issues, so that we may add them to the project.

The information below this line is considered archived for future reference.

---

Tracking issue for performance/profiling issues

- [ ] #1310 core: skip chassis locking for methods that aren't implemented 

- [ ] Mutex performance/serialization
    In several tests, half the total cycles during validation are spent in mutex wait. Aside for the performance impact, this imposed serialization has a dramatic "observer effect" changing the timing and ordering of application thread execution.
    Possible actions -- Reader writer locks.  Minimization of lock times (lock per data structure, batched updates, other.) 

- [ ] Shader Module Validation
    Can add minutes to validation start up time.  Appears to repeatedly traverse/evaluate the shader information.  Assessment is needed as to identify hot spot and structural performance issues.  Consider moving work (where possible) to CreateShaderModule instead of Create*Pipeline.  Consider collecting shader data once for easy lookup later instead of traversing SPIR-V multiple times.  Look for ways to avoid calling spirv optimizer and spirv validator multiple times.

- [ ] “Shallow” binding and tracking of resources at command record time
    Currently if a VkImageView (or VkBufferView)  is referenced by a command buffer, we also add cross references and in_use updates for all related objects such as VkImage (or VkBuffer) and VkMemory).  If instead VkImageView, VkBufferView were updated, the operations that check for references of the related objects (VkImage, VkBuffer, VkMemory) would be able to determine their state (at reset or queue submit *validation* time) by traversing references to the orginal objects.  As this will typically be less frequent than draw command recording, and only apply to validation operations, this should reduce overall bookkeeping overhead.

- [ ] Store queue_family_index in GLOBAL_CB_NODE  (unless VkPool reference is "dehandled".)
- [ ] Convert global image layout tracking to the faster version used in command buffer image layout tracking. (Also, work to minimize the "new" overhead for both the iterators and lambda used in the new design.)
- [ ] Improve layer memory allocation/free patterns for identified hotspots by migrating from new/delete to memory pooling or other alternative(s)
- [ ] #846 Contention on data structure guarding mutexes
     Consider looking at Vulkan external sync API requirements to reduce locking.
- [ ] #2188 Migrate STD to Abseil
- [ ] Minimize hash table lookups (continuation of work done in #1296)
- [ ] Add instrumentation to chassis module for finer-grained execution statistics collection
- [ ] Implement validation cache for shaders
- [ ] Consider not validating every frame - could skip frames that are determined to not change much without too much of a risk of missing something
- [ ] Use threads in validation layer to improve throughput

# Implemented Items

- [X] Remove shadow memory copy
- [x] Internal inter-object reference with pointers instead of Vk* object handles (AKA - 'dehandling')
    Currently for cross-object reference, the Vk* handle is used (for example for a descriptor with an VkImageView to reference the VkImage it is a view of it is needed to call GetImageViewState and GetImageState)
    New approach    (Fixes in: #1400 #1411 #1425)
    * For each object with cross-reference, store state as a shared_ptr in map (instead of as emplaced object, plain, or unique_ptr).  
    * Each object that references gets a copy of that pointer.
    * During locked operations only the .get() plain pointer is used (for performance reasons, you don’t want to keep creating/passing additional shared pointers, but is guaranteed to be non-null based on this design. (Passing a shared_ptr by value causes multiple atomic operations.)
    * Add an IsDeleted (or is_deleted) method (or field) to the referenced object state to track/report uses of delete objects (descriptor_set does this already)
    * On object delete, shared ptr is removed from the map (but any outstanding references remain valid) – mark as deleted
    * Approach also avoids handle aliasing for deleted and recreated resources when object handle wrapping is disabled.
- [x] Minimize "FromBinding" repeated hash lookups (Fix in #1296)
    Currently binding meta information is obtained from binding number hash lookup -- for example
    - HasBinding check
    - GlobalRangeFromBinding
    - GetDescriptorFlagsFromBinding 
- [x] Eliminate lookup of descriptor contents that are invariant between UpdateDescriptorSet 
    Another example of "dehandling* -- when updating descriptors fetch the state date (e.g. GetImageViewState, GetBufferViewState) and store results in the descriptor instead of the handles. 
- [x] #1192 Memory pool optimization of safe structs

**Comment by jeffbolznv** [comment]
Regarding the shader module validation, most of the loops iterate over all instructions even though they only care about instructions that must be placed before the first function definition. It should be easy to make these all terminate early.

**Comment by mark-lunarg** [comment]
@jeremy-lunarg, this should be some low-hanging fruit if you would like another challenge.

**Comment by tobine** [comment]
Added a memory allocation bullet to the original tracking list. Will append further info to direct optimization work in this area. @aellem

**Comment by jeffbolznv** [comment]
The safe structs allocated in the dispatch chassis are a great candidate for a memory pool optimization. There was some discussion of that (and a prototype) here: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/1192#discussion_r317382934.

**Comment by locke-lunarg** [comment]
Internal inter-object reference with pointers instead of Vk* object handles (AKA - 'dehandling')
Eliminate lookup of descriptor contents that are invariant between UpdateDescriptorSet

Looks done.

**Comment by mark-lunarg** [comment]
@jeremy-lunarg and I were talking about the validation cache extension -- it may be possible to implement this as a feature in corechecks which would run by default.  This should significantly cut down startup times on apps that do not choose to implement that extension.  In such a case, we'd need to defer any internal caching if the extension WAS enabled, but it should be possible to do, and to possibly extend to the specialization constant validation pass at CreatePipelines-time.

**Comment by mark-lunarg** [comment]
Adding issue #2188, which might improve performance for some standard library usage.

**Comment by karl-lunarg** [comment]
This tracking issue is now closed.

All Validation Layer Performance information is now tracked via the Validation Layer Performance project [page](https://github.com/KhronosGroup/Vulkan-ValidationLayers/projects/6).
