### ISSUE TITLE
syncval: Performance tracking issue

### ISSUE THREAD

**Issue by jzulauf-lunarg** [KhronosGroup/Vulkan-ValidationLayers#2257]
This issue is used to track know areas for potential performance optimization.

- Range Generation
  - [ ] RangeGeneration Constructor -- copy from image or view for full extent/full subresource range in image/view
  - [ ] Specialization/Overload/Derived class for full extent (simplify constructor/++)
- Range traversal
  - [ ] Minimize Subpass DAG walks for lazy access context evaluation -- full extent "ResolveAccess" when safe (state is modified) either in subresource or index space (i.e. set descent range to [min_index, max_index) )
- Range map usage patterns
  - [ ] Replace upper bound iterator loop conditions with range comparison
  - [ ] minimize iterator copy, unused increment paths

**Comment by jzulauf-lunarg** [comment]
Moved to Sync Val project.
