### ISSUE TITLE
Look into other promoted extensions missing a feature bit

### ISSUE THREAD

**Issue by sfricke-samsung** [KhronosGroup/Vulkan-ValidationLayers#2619]
**Describe the situation in which you encountered the missing validation**
Issue description: After doing the mental exercise in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2605 I plan to quickly go through the other extensions that were promoted to Vulkan 1.1/1.2 that didn't have a dedicated feature bit and make sure they are not suffering from the same issue as `drawIndirectCount` was. I Will also write a variation of a test for them if we don't them already (We have some variation tests for them, but haven't looked in a while)

**Valid Usage IDs requested**
Please include the valid usage IDs for the checks you are requesting: N/A

**Additional Context**
Any additional information: All promoted features from `Extension Feature Aliases` table

- [x] shaderDrawParameters - SPIR-V Capability (add test) #2938
- [x] drawIndirectCount - #2605
- [x] samplerMirrorClampToEdge #2937
- [x] descriptorIndexing - nothing to validated
- [ ] samplerFilterMinmax - No validation yet (need to add VU to spec) https://gitlab.khronos.org/vulkan/vulkan/-/issues/2747
- [x] shaderOutputViewportIndex, shaderOutputLayer  - SPIR-V Capability (same as `shaderDrawParameters`) #2938

**Comment by sjfricke** [comment]
`VUID-VkSamplerCreateInfo-pNext-06726` was added in 1.3.211 and should address the last part of this issue (`samplerFilterMinmax`)
