### ISSUE TITLE
Missing runtime atomic feature validation check

### ISSUE THREAD

**Issue by sfricke-samsung** [KhronosGroup/Vulkan-ValidationLayers#2629]
**Describe the situation in which you encountered the missing validation**
Issue description: Currently there is no coverage of `VK_EXT_shader_atomic_float`, `VK_EXT_shader_atomic_float2`, `VK_EXT_shader_image_atomic_int64`, or `VK_KHR_shader_atomic_int64` feature bits to see if the SPIR-V is allowed to use the various forms of atomics

**Valid Usage IDs requested**
Please include the valid usage IDs for the checks you are requesting: (currently no VUID for runtime SPIR-V validation)

**Additional Context**
Any additional information: I have been slowly working on this with the Working Group to clarify various parts of the specifications around these atomic feature bits. I have some basic tests is written up and implementation ready. Creating issue to mark that this is being worked on and will be up when spec language is ironed out

Adding for search-ability
- [x] VK_KHR_shader_atomic_int64 (#3094)
    - [x]       shaderBufferInt64Atomics
    - [x]      shaderSharedInt64Atomics
- [x] VK_EXT_shader_image_atomic_int64
    - [x]      shaderImageInt64Atomics (#3125)
    - [x]       sparseImageInt64Atomics
- [x] VK_EXT_shader_atomic_float (#3209)
    - [x]       shaderBufferFloat32Atomics
    - [x]       shaderBufferFloat32AtomicAdd
    - [x]       shaderBufferFloat64Atomics
    - [x]       shaderBufferFloat64AtomicAdd
    - [x]       shaderSharedFloat32Atomics
    - [x]       shaderSharedFloat32AtomicAdd
    - [x]       shaderSharedFloat64Atomics
    - [x]       shaderSharedFloat64AtomicAdd
    - [x]       shaderImageFloat32Atomics
    - [x]       shaderImageFloat32AtomicAdd
    - [x]       sparseImageFloat32Atomics
    - [x]       sparseImageFloat32AtomicAdd
- [x] VK_EXT_shader_atomic_float2 (#3209)
    - [x]       shaderBufferFloat16Atomics
    - [x]       shaderBufferFloat16AtomicAdd
    - [x]       shaderBufferFloat16AtomicMinMax
    - [x]       shaderBufferFloat32AtomicMinMax
    - [x]       shaderBufferFloat64AtomicMinMax
    - [x]       shaderSharedFloat16Atomics
    - [x]       shaderSharedFloat16AtomicAdd
    - [x]       shaderSharedFloat16AtomicMinMax
    - [x]       shaderSharedFloat32AtomicMinMax
    - [x]       shaderSharedFloat64AtomicMinMax
    - [x]       shaderImageFloat32AtomicMinMax
    - [x]       sparseImageFloat32AtomicMinMax
- [ ] VUID-RuntimeSpirv-None-06283 (sparseImageFloat32AtomicAdd)
- [ ] VUID-RuntimeSpirv-None-06287 (sparseImageFloat32AtomicAdd)

**Comment by spencer-lunarg** [comment]
The final 2 VUs are being clarified in the WG and most likely will change, going to close issue as main scope of issue has been covered
