### ISSUE TITLE
GPU Assisted Validation Opportunities Tracking Issue

### ISSUE THREAD

**Issue by Tony-LunarG** [KhronosGroup/Vulkan-ValidationLayers#852]
This issue is to list and keep track of future opportunities in GPU assisted validation

- [ ] Remove the use of an extra descriptor set by using the VK_EXT_buffer_device_address extension to obtain a GPU device pointer to a storage buffer and make it available to the shader via a specialization constant.
- [ ] Remove the use of an extra descriptor set by adding the debug descriptors to an existing descriptor set 
- [ ] Extend OOB and unwritten descriptor validation to more descriptor types, buffers being the next planned priority
- [ ] Add layout checking of dynamically accessed layers
- [ ] Intra-buffer bounds checking
- [ ] Once buffer validation is complete, make sure that all of the concerns in PR #779 have been addressed
- [ ] Add Label / Marker info to GPU-AV error messages
- [ ] EXT_buffer_device_address pointer OOB validation
- [ ] Layout validation with descriptor indexing extension
- [ ] Validation of inline uniform blocks with descriptor indexing
- [ ] More control over where and at what severity level debug printf messages are delivered

**Comment by KarenGhavam-lunarG** [comment]
@Tony-LunarG Could you add the following to the task list (I don't have write access):
1. Intra-buffer bounds checking
2. debug printf - debug information will be printed if layers enabled. If layers not enabled, noop.

**Comment by mark-lunarg** [comment]
The items in this issue are now being tracked in [this repositories project pages](https://github.com/KhronosGroup/Vulkan-ValidationLayers/projects/3).  Please reference that for current status.
